name: PullRequest

on: [ pull_request ]

jobs:
  buildTest:
    name: Build & Test JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    defaults:
      run:
        shell: bash
        working-directory: android
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Run tests
        run: ./gradlew test
      #      - name: Run instrumentation tests
      #        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
      #        with:
      #          cmd: ./gradlew cAT
      #          api: 28
      #          tag: default
      #          abi: x86
      #      - name: Archive Espresso results
      #        uses: actions/upload-artifact@v2.2.0
      #        with:
      #          name: FFMPEG-Espresso-report
      #          path: app/build/reports/androidTests/connected
      #      - name: Save logcat output
      #        uses: actions/upload-artifact@master
      #        if: failure()
      #        with:
      #          name: FFMPEG-logcat
      #          path: artifacts/logcat.log
  buildRelease:
    name: Build release JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    defaults:
      run:
        shell: bash
        working-directory: android
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Build project
        run: ./gradlew assembleRelease
  Check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: android
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v4.6.2
        if: ${{ always() }}
        with:
          name: FFMPEG-Lint-report
          path: |
            ./**/build/reports/lint-results.html
            ./**/**/build/reports/lint-results.html
  TestJitpack:
    name: Test jitpack.io
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: android
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17
      - name: Code checks
        run: ./gradlew :ffmpeg-kit-android-lib:build :ffmpeg-kit-android-lib:publishToMavenLocal -x :ffmpeg-kit-android-lib:test
      - name: Find artifactds
        run: find . -name "*.aar"
